# Site settings
title: 'Wolfgang Teuber'
description: Focus - Passion - Innovation
url: 'https://wteuber.com'
baseurl: ''
google_analytics: 'G-HNQ41FEKY5'

author:
  name: 'Wolfgang Teuber'
  github_username: wteuber
  linkedin_username: wolfgang-teuber
  twitter_username: wolfgang_teuber

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
